ALTER TABLE metric_snapshots
    ADD COLUMN IF NOT EXISTS gpu_usage DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS battery_percent DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS container_cpu_usage DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS container_memory_usage DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS fans_json TEXT,
    ADD COLUMN IF NOT EXISTS batteries_json TEXT,
    ADD COLUMN IF NOT EXISTS gpus_json TEXT;
