ALTER TABLE metric_snapshots
    ADD COLUMN IF NOT EXISTS smart_passed INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS smart_failed INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS smart_unknown INTEGER NOT NULL DEFAULT 0;
