[CmdletBinding()]
param(
    [switch] $Overwrite,
    [switch] $AllowLocalHttp,
    [switch] $AllowInsecureHttp
)

$ErrorActionPreference = 'Stop'
$projectRoot = Split-Path -Parent $PSScriptRoot
$envPath = Join-Path $projectRoot '.env'

if (-not (Get-Command docker -ErrorAction SilentlyContinue)) { throw '需要安装 Docker Engine。' }
& docker compose version | Out-Null
if ($LASTEXITCODE -ne 0) { throw '需要 Docker Compose v2。' }
if ((Test-Path -LiteralPath $envPath) -and -not $Overwrite) {
    throw '.env 已存在。请手动编辑，或使用 -Overwrite 覆盖并自动备份。'
}

function Read-Required([string] $Label) {
    do { $value = Read-Host $Label } while ([string]::IsNullOrWhiteSpace($value))
    return $value.Trim()
}

function Read-Secret([string] $Label) {
    do {
        $secure = Read-Host "$Label（至少 12 位）" -AsSecureString
        $value = [Net.NetworkCredential]::new('', $secure).Password
    } while ($value.Length -lt 12)
    return $value
}

function New-HexSecret {
    $bytes = [byte[]]::new(32)
    $random = [Security.Cryptography.RandomNumberGenerator]::Create()
    try { $random.GetBytes($bytes) } finally { $random.Dispose() }
    return (($bytes | ForEach-Object { $_.ToString('x2') }) -join '')
}

function New-Base64Secret {
    $bytes = [byte[]]::new(32)
    $random = [Security.Cryptography.RandomNumberGenerator]::Create()
    try { $random.GetBytes($bytes) } finally { $random.Dispose() }
    return [Convert]::ToBase64String($bytes)
}

$publicBaseUrl = Read-Required '公网入口 URL（HTTPS）'
try { $uri = [Uri]$publicBaseUrl } catch { throw '公网入口 URL 格式无效。' }
$localHttp = $uri.Scheme -eq 'http' -and @('localhost', '127.0.0.1', '::1') -contains $uri.Host
if ([string]::IsNullOrWhiteSpace($uri.Host) -or $uri.Query -or $uri.Fragment -or ($uri.Scheme -ne 'https' -and -not (($AllowInsecureHttp -and $uri.Scheme -eq 'http') -or ($AllowLocalHttp -and $localHttp)))) {
    throw '公网入口必须是 HTTPS；临时 IP/HTTP 初始化请使用 -AllowInsecureHttp。'
}
if ($AllowInsecureHttp -and $uri.Scheme -eq 'http' -and -not $localHttp) {
    Write-Warning '当前使用明文 HTTP，仅限初始化。绑定 HTTPS 域名后必须更新 .env 并重建 server。'
}
$allowedOrigins = Read-Required 'Web 来源（通常与公网入口相同）'
$siteName = Read-Required '站点名称'
$adminUsername = Read-Required '初始管理员用户名'
$timezone = Read-Required '服务时区（例如 Asia/Shanghai）'
$webPort = Read-Required 'Web 端口（1-65535）'
if ($webPort -notmatch '^[0-9]+$' -or [int]$webPort -lt 1 -or [int]$webPort -gt 65535) { throw 'Web 端口无效。' }
$webBindAddress = Read-Required 'Web 绑定地址（0.0.0.0 允许 IP 直连；127.0.0.1 仅供宝塔反代）'
if ($webBindAddress -notin @('0.0.0.0', '127.0.0.1', 'localhost', '::1')) { throw 'Web 绑定地址只支持 0.0.0.0、127.0.0.1、localhost 或 ::1。' }
$adminPassword = Read-Secret '初始管理员密码'
$adminPasswordConfirm = Read-Secret '再次输入初始管理员密码'
if ($adminPassword -cne $adminPasswordConfirm) { throw '两次管理员密码不一致。' }

$dbUrl = Read-Required '外部 MySQL JDBC URL（同机用 host.docker.internal，例如 jdbc:mysql://host.docker.internal:3306/monitor?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC）'
if ($dbUrl -notmatch '^jdbc:mysql://[^\s]+$') { throw '数据库 URL 必须是 jdbc:mysql:// 开头的 JDBC 地址。' }
$dbUsername = Read-Required '数据库用户名'
$dbPassword = Read-Secret '数据库密码'
$dbPasswordConfirm = Read-Secret '再次输入数据库密码'
if ($dbPassword -cne $dbPasswordConfirm) { throw '两次数据库密码不一致。' }
$settingsKey = New-Base64Secret
$secureLines = @(
    '# Generated by deploy/install-controller.ps1. Keep this file private.'
    "DB_URL=$dbUrl"
    "DB_USERNAME=$dbUsername"
    "DB_PASSWORD=$dbPassword"
    "BOOTSTRAP_ADMIN_USERNAME=$adminUsername"
    "BOOTSTRAP_ADMIN_PASSWORD=$adminPassword"
    "SETTINGS_ENCRYPTION_KEY=$settingsKey"
    "WEB_PORT=$webPort"
    "WEB_BIND_ADDRESS=$webBindAddress"
    "APP_TIMEZONE=$timezone"
    "SITE_NAME=$siteName"
    "PUBLIC_BASE_URL=$publicBaseUrl"
    "SESSION_COOKIE_SECURE=$($uri.Scheme -eq 'https')"
    "ALLOW_INSECURE_HTTP=$($uri.Scheme -eq 'http')"
    "ALLOWED_ORIGINS=$allowedOrigins"
    'METRIC_RETENTION_DAYS=30'
    'DEVICE_OFFLINE_AFTER_SECONDS=30'
)
$tmpPath = Join-Path ([IO.Path]::GetTempPath()) ("guanlan-env-{0}.tmp" -f [Guid]::NewGuid().ToString('N'))
try {
    [IO.File]::WriteAllLines($tmpPath, $secureLines, [Text.UTF8Encoding]::new($false))
    if (Test-Path -LiteralPath $envPath) {
        Copy-Item -LiteralPath $envPath -Destination "$envPath.backup.$(Get-Date -Format yyyyMMddHHmmss)"
    }
    Move-Item -LiteralPath $tmpPath -Destination $envPath -Force
    & icacls.exe $envPath /inheritance:r /grant:r 'SYSTEM:(F)' 'Administrators:(F)' | Out-Null
    if ($LASTEXITCODE -ne 0) { throw '.env 权限收紧失败。' }
    & docker compose --env-file $envPath config --quiet
    if ($LASTEXITCODE -ne 0) { throw 'Compose 配置校验失败。' }
    & docker compose --env-file $envPath up --build -d
    if ($LASTEXITCODE -ne 0) { throw '总终端服务器启动失败。' }
    Write-Host "总终端服务器已启动。请打开 $publicBaseUrl 并使用刚设置的管理员账号登录。"
}
finally {
    if (Test-Path -LiteralPath $tmpPath) { Remove-Item -LiteralPath $tmpPath -Force }
    Remove-Variable adminPassword, adminPasswordConfirm, dbPassword, dbPasswordConfirm, settingsKey -ErrorAction SilentlyContinue
}
