#!/usr/bin/env bash
set -euo pipefail

usage() {
  echo "Usage: $0 [--overwrite] [--allow-local-http] [--allow-insecure-http]"
}

overwrite=false
allow_local_http=false
allow_insecure_http=false
while [[ $# -gt 0 ]]; do
  case "$1" in
    --overwrite) overwrite=true; shift ;;
    --allow-local-http) allow_local_http=true; shift ;;
    --allow-insecure-http) allow_insecure_http=true; shift ;;
    --help|-h) usage; exit 0 ;;
    *) echo "Unknown option: $1" >&2; usage >&2; exit 2 ;;
  esac
done

script_dir="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
project_root="$(cd -- "${script_dir}/.." && pwd)"
env_file="${project_root}/.env"

if ! command -v docker >/dev/null 2>&1 || ! docker compose version >/dev/null 2>&1; then
  echo "Docker Engine and Docker Compose v2 are required." >&2
  exit 1
fi
if [[ -f "${env_file}" && "${overwrite}" != true ]]; then
  echo ".env already exists. Edit it manually or rerun with --overwrite." >&2
  exit 1
fi

ask() {
  local label="$1" value=""
  while [[ -z "${value}" ]]; do
    read -r -p "${label}: " value
  done
  printf '%s' "${value}"
}

ask_secret() {
  local label="$1" value=""
  while [[ ${#value} -lt 12 ]]; do
    read -r -s -p "${label} (至少 12 位): " value
    echo >&2
  done
  printf '%s' "${value}"
}

if ! command -v openssl >/dev/null 2>&1; then
  echo "OpenSSL is required to generate deployment secrets." >&2
  exit 1
fi
random_hex() { openssl rand -hex 32 | tr -d '\n'; }

public_base_url="$(ask '公网入口 URL（HTTPS）')"
if [[ ! "${public_base_url}" =~ ^https://[^/?#[:space:]]+(/[^?#[:space:]]*)?$ ]]; then
  if [[ "${allow_insecure_http}" == true && "${public_base_url}" =~ ^http://[^/?#[:space:]]+(:[0-9]+)?(/[^?#[:space:]]*)?$ ]]; then
    echo "警告：当前使用明文 HTTP，仅限初始化。绑定 HTTPS 域名后必须更新 .env 并重建 server。" >&2
  elif [[ "${allow_local_http}" == true && "${public_base_url}" =~ ^http://(localhost|127\.0\.0\.1)(:[0-9]+)?(/[^?#[:space:]]*)?$ ]]; then
    :
  else
    echo "公网入口必须是 HTTPS；临时 IP/HTTP 初始化请使用 --allow-insecure-http。" >&2
    exit 2
  fi
fi
allowed_origins="$(ask 'Web 来源（通常与公网入口相同）')"
site_name="$(ask '站点名称')"
admin_username="$(ask '初始管理员用户名')"
timezone="$(ask '服务时区（例如 Asia/Shanghai）')"
web_port="$(ask 'Web 端口（1-65535）')"
if [[ ! "${web_port}" =~ ^[0-9]+$ ]] || (( web_port < 1 || web_port > 65535 )); then
  echo "Web 端口无效。" >&2
  exit 2
fi
web_bind_address="$(ask 'Web 绑定地址（0.0.0.0 允许 IP 直连；127.0.0.1 仅供宝塔反代）')"
if [[ ! "${web_bind_address}" =~ ^(0\.0\.0\.0|127\.0\.0\.1|localhost|::1)$ ]]; then
  echo "Web 绑定地址只支持 0.0.0.0、127.0.0.1、localhost 或 ::1。" >&2
  exit 2
fi
admin_password="$(ask_secret '初始管理员密码')"
admin_password_confirm="$(ask_secret '再次输入初始管理员密码')"
if [[ "${admin_password}" != "${admin_password_confirm}" ]]; then
  echo "两次管理员密码不一致。" >&2
  exit 2
fi

tmp_file="$(mktemp)"
trap 'rm -f "${tmp_file}"; unset admin_password admin_password_confirm db_password db_password_confirm settings_key' EXIT
db_url="$(ask '外部 MySQL JDBC URL（例如 jdbc:mysql://127.0.0.1:3306/monitor?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC）')"
if [[ ! "${db_url}" =~ ^jdbc:mysql://[^[:space:]]+$ ]]; then
  echo "数据库 URL 必须是 jdbc:mysql:// 开头的 JDBC 地址。" >&2
  exit 2
fi
db_username="$(ask '数据库用户名')"
db_password="$(ask_secret '数据库密码')"
db_password_confirm="$(ask_secret '再次输入数据库密码')"
if [[ "${db_password}" != "${db_password_confirm}" ]]; then
  echo "两次数据库密码不一致。" >&2
  exit 2
fi
settings_key="$(openssl rand -base64 32 | tr -d '\n')"
umask 077
cat > "${tmp_file}" <<EOF
# Generated by deploy/install-controller.sh. Keep this file private.
DB_URL=${db_url}
DB_USERNAME=${db_username}
DB_PASSWORD=${db_password}
BOOTSTRAP_ADMIN_USERNAME=${admin_username}
BOOTSTRAP_ADMIN_PASSWORD=${admin_password}
SETTINGS_ENCRYPTION_KEY=${settings_key}
WEB_PORT=${web_port}
WEB_BIND_ADDRESS=${web_bind_address}
APP_TIMEZONE=${timezone}
SITE_NAME=${site_name}
PUBLIC_BASE_URL=${public_base_url}
SESSION_COOKIE_SECURE=$([[ "${public_base_url}" == https://* ]] && echo true || echo false)
ALLOW_INSECURE_HTTP=$([[ "${public_base_url}" == http://* ]] && echo true || echo false)
ALLOWED_ORIGINS=${allowed_origins}
METRIC_RETENTION_DAYS=30
DEVICE_OFFLINE_AFTER_SECONDS=30
EOF

if [[ -f "${env_file}" && "${overwrite}" == true ]]; then
  cp -- "${env_file}" "${env_file}.backup.$(date +%Y%m%d%H%M%S)"
fi
install -m 0600 "${tmp_file}" "${env_file}"
docker compose --env-file "${env_file}" config --quiet
docker compose --env-file "${env_file}" up --build -d
echo "总终端服务器已启动。请打开 ${public_base_url} 并使用刚设置的管理员账号登录。"
