[CmdletBinding()]
param(
    [switch] $Help,
    [switch] $Cleanup,
    [switch] $Build,
    [switch] $SourceBuild,
    [switch] $Offline,
    [switch] $AutoUpdate,
    [switch] $NoMirror,
    [switch] $NoSourceFallback
)

$ErrorActionPreference = 'Stop'

if ($Help) {
    @'
Usage: install-controller.ps1 [-Cleanup] [-Build | -SourceBuild] [-Offline]

Pulls prebuilt controller images and starts the controller with an internal
PostgreSQL database. Site and administrator configuration are completed in the
browser guide at /setup.

-Cleanup stops this Compose project and removes its local images before build.
         PostgreSQL and Redis volumes are preserved.
-Build builds controller images locally instead of pulling them from GHCR.
-SourceBuild builds Docker images from Gitee/GitHub source repositories.
-Offline uses only images already loaded into the local Docker engine.
-AutoUpdate enables the controller's daily 04:00 automatic update.
-NoMirror skips mainland-China mirror registries and uses official GHCR.
-NoSourceFallback does not build from source when all image registries fail.
'@
    exit 0
}

$projectRoot = Split-Path -Parent $PSScriptRoot
if ($Build -and $SourceBuild) { throw '-Build 与 -SourceBuild 不能同时使用。' }
if ($Offline -and ($Build -or $SourceBuild -or $AutoUpdate)) { throw '-Offline 不能与 -Build、-SourceBuild 或 -AutoUpdate 同时使用。' }
if (-not (Get-Command docker -ErrorAction SilentlyContinue)) { throw '需要安装 Docker Engine。' }
& docker compose version | Out-Null
if ($LASTEXITCODE -ne 0) { throw '需要 Docker Compose v2。' }

Push-Location $projectRoot
try {
    $envFile = Join-Path $projectRoot '.env'
    $utf8NoBom = New-Object System.Text.UTF8Encoding($false)
    $newPassword = {
        $bytes = New-Object byte[] 32
        $generator = [System.Security.Cryptography.RandomNumberGenerator]::Create()
        try { $generator.GetBytes($bytes) } finally { $generator.Dispose() }
        return -join ($bytes | ForEach-Object { $_.ToString('x2') })
    }
    $writeBootstrapEnv = {
        $password = & $newPassword
        $lines = @(
            '# Generated by the controller installer. Keep this file private.'
            'SPRING_PROFILES_ACTIVE=bootstrap'
            'POSTGRES_DB=xingchen_monitor'
            'POSTGRES_USER=xingchen'
            "POSTGRES_PASSWORD=$password"
            'CONTROLLER_AGENT_ENABLED=false'
        )
        [System.IO.File]::WriteAllLines($envFile, $lines, $utf8NoBom)
    }

    if (-not (Test-Path -LiteralPath $envFile)) {
        & $writeBootstrapEnv
    }
    elseif (-not (Select-String -LiteralPath $envFile -Pattern '^POSTGRES_PASSWORD=("[^"]+"|\S+)$' -Quiet)) {
        & $writeBootstrapEnv
    }
    function Set-InstallerSetting([string] $Name, [string] $Value) {
        if ($Value.Contains("`r") -or $Value.Contains("`n")) { throw "$Name 不能包含换行符。" }
        $lines = [System.Collections.Generic.List[string]]::new()
        $found = $false
        foreach ($line in [System.IO.File]::ReadAllLines($envFile)) {
            if ($line.StartsWith("$Name=")) {
                if (-not $found) { [void] $lines.Add("$Name=`"$Value`"") }
                $found = $true
            }
            else { [void] $lines.Add($line) }
        }
        if (-not $found) { [void] $lines.Add("$Name=`"$Value`"") }
        $temporary = Join-Path $projectRoot ('.env.controller-install.' + [Guid]::NewGuid().ToString('N'))
        try {
            [System.IO.File]::WriteAllLines($temporary, $lines, $utf8NoBom)
            Move-Item -LiteralPath $temporary -Destination $envFile -Force
        }
        finally {
            if (Test-Path -LiteralPath $temporary) { Remove-Item -LiteralPath $temporary -Force }
        }
    }
    if (-not (Select-String -LiteralPath $envFile -Pattern '^COMPOSE_PROJECT_NAME=' -Quiet)) {
        $legacyDatabase = Select-String -LiteralPath $envFile -Pattern '^POSTGRES_DB=["'']?(.*?)["'']?$' | Select-Object -First 1
        $legacyVolume = (& docker volume inspect 'guanlan-monitor_postgres-data' 2>$null)
        $projectName = if (($legacyDatabase -and $legacyDatabase.Matches[0].Groups[1].Value -eq 'guanlan_monitor') -or $legacyVolume) { 'guanlan-monitor' } else { 'xingchen-monitor' }
        [System.IO.File]::AppendAllText($envFile, "COMPOSE_PROJECT_NAME=$projectName`r`n", $utf8NoBom)
    }
    $installerSettings = @(
        'XINGCHEN_POSTGRES_IMAGE', 'XINGCHEN_REDIS_IMAGE',
        'XINGCHEN_SETUP_IMAGE', 'XINGCHEN_SERVER_IMAGE', 'XINGCHEN_WEB_IMAGE', 'XINGCHEN_AGENT_IMAGE',
        'XINGCHEN_TARGET_VERSION', 'XINGCHEN_RELEASE_MANIFEST_PATH', 'XINGCHEN_RELEASE_MANIFEST_URLS', 'XINGCHEN_RELEASE_MANIFEST_SHA256',
        'XINGCHEN_AGENT_RELEASE_BASE_URLS', 'XINGCHEN_AGENT_CACHE_DIR', 'XINGCHEN_AGENT_OFFLINE_DIR',
        'XINGCHEN_CONTROLLER_ALLOW_GITHUB_API', 'XINGCHEN_CONTROLLER_IMAGE_MIRRORS', 'XINGCHEN_AGENT_IMAGE_MIRRORS',
        'XINGCHEN_SOURCE_REPOSITORIES', 'XINGCHEN_SOURCE_REF', 'XINGCHEN_SOURCE_BUILD_TIMEOUT_SECONDS',
        'XINGCHEN_UPDATE_MIRROR_TIMEOUT_SECONDS', 'XINGCHEN_UPDATE_PULL_TIMEOUT_SECONDS', 'XINGCHEN_UPDATE_COMPOSE_TIMEOUT_SECONDS', 'XINGCHEN_UPDATE_MIN_FREE_BYTES'
    )
    foreach ($name in $installerSettings) {
        $value = [Environment]::GetEnvironmentVariable($name)
        if (-not [string]::IsNullOrWhiteSpace($value)) { Set-InstallerSetting $name $value }
    }
    if ($Offline) {
        $manifestPath = [Environment]::GetEnvironmentVariable('XINGCHEN_RELEASE_MANIFEST_PATH')
        $offlineDir = [Environment]::GetEnvironmentVariable('XINGCHEN_AGENT_OFFLINE_DIR')
        $manifestHostPath = if ($manifestPath -and $manifestPath.StartsWith('/workspace/')) { Join-Path $projectRoot $manifestPath.Substring('/workspace/'.Length).Replace('/', [IO.Path]::DirectorySeparatorChar) } else { $manifestPath }
        $offlineHostDir = if ($offlineDir -and $offlineDir.StartsWith('/workspace/')) { Join-Path $projectRoot $offlineDir.Substring('/workspace/'.Length).Replace('/', [IO.Path]::DirectorySeparatorChar) } else { $offlineDir }
        if (-not $manifestHostPath -or -not (Test-Path -LiteralPath $manifestHostPath -PathType Leaf)) { throw "离线 Release manifest 不存在：$manifestPath" }
        if (-not $offlineHostDir -or -not (Test-Path -LiteralPath $offlineHostDir -PathType Container)) { throw "离线 Agent 制品目录不存在：$offlineDir" }
    }
    & docker compose config --quiet
    if ($LASTEXITCODE -ne 0) { throw 'Compose 配置校验失败。' }

    if ($Cleanup) {
        Write-Host '清理星辰监控旧容器和镜像（保留 PostgreSQL/Redis 卷）...'
        & docker compose down --remove-orphans --rmi local
        if ($LASTEXITCODE -ne 0) { throw '旧项目资源清理失败。' }
        $projectImageIds = @(& docker image ls --format '{{.Repository}} {{.ID}}' | ForEach-Object {
            $parts = $_ -split '\s+'
            if ($parts.Count -ge 2 -and $parts[0] -match '^(xingchen|guanlan)-monitor(-|$)') { $parts[1] }
        } | Sort-Object -Unique)
        foreach ($imageId in $projectImageIds) {
            if ($imageId) { & docker image rm -f $imageId | Out-Null }
        }
    }

    $controllerServices = @('setup', 'server', 'web')
    if ($Build) {
        Write-Host '使用本地源码构建总控镜像...'
        & docker compose build --pull $controllerServices
    }
    else {
        Write-Host '正在拉取总控预构建镜像（优先使用国内镜像源）...'
        $updateScript = Join-Path $PSScriptRoot 'update-controller.ps1'
        $updateArgs = @('-Check')
        if ($Offline) { $updateArgs += '-Offline' }
        if ($SourceBuild) { $updateArgs += '-SourceBuild' }
        if ($NoMirror) { $updateArgs += '-NoMirror' }
        if ($NoSourceFallback) { $updateArgs += '-NoSourceFallback' }
        & $updateScript @updateArgs
    }
    if ($LASTEXITCODE -ne 0) { throw '总控镜像准备失败；如需本地构建请重试 -Build。' }
    & docker compose up -d --remove-orphans
    if ($LASTEXITCODE -ne 0) { throw '总终端服务器启动失败。' }

    $webPort = 18080
    if (Test-Path -LiteralPath $envFile) {
        $portLine = Select-String -LiteralPath $envFile -Pattern '^WEB_PORT=["'']?([0-9]+)["'']?$' | Select-Object -First 1
        if ($portLine -and $portLine.Matches[0].Groups[1].Value) {
            $webPort = [int]$portLine.Matches[0].Groups[1].Value
        }
    }
    $healthy = $false
    for ($attempt = 1; $attempt -le 40; $attempt++) {
        try {
            $health = Invoke-WebRequest -UseBasicParsing -Uri "http://127.0.0.1:$webPort/healthz" -TimeoutSec 3
            if ($health.StatusCode -eq 200) { $healthy = $true; break }
        }
        catch { }
        Start-Sleep -Seconds 3
    }
    if (-not $healthy) { throw 'Web 服务未在 120 秒内通过健康检查，请运行 docker compose ps 和 docker compose logs。' }
}
finally {
    Pop-Location
}

Write-Host "总终端服务器已启动。首次安装请打开 http://<服务器IP>:$webPort/setup。"
Write-Host "安装完成后，直接访问配置的域名根路径即可进入公开状态页，无需追加 /status。"
Write-Host 'PostgreSQL 已内置，数据库凭据由安装器自动生成，无需填写或执行数据库命令。'
Write-Host '向导只需设置站点入口、来源、时区和首个管理员。端口与绑定地址已在总终端启动前确定。'
Write-Host 'Windows 总终端默认不自动采集宿主机；请在设备管理中按普通 Windows Agent 流程接入。'
if ($AutoUpdate) {
    & (Join-Path $PSScriptRoot 'update-controller.ps1') -Auto
}
