[CmdletBinding()]
param(
    [switch] $Help,
    [switch] $Cleanup,
    [switch] $Build,
    [switch] $SourceBuild,
    [switch] $AutoUpdate,
    [switch] $NoMirror,
    [switch] $NoSourceFallback
)

$ErrorActionPreference = 'Stop'

if ($Help) {
    @'
Usage: install-controller.ps1 [-Cleanup] [-Build | -SourceBuild]

Pulls prebuilt controller images and starts the controller with an internal
PostgreSQL database. Site and administrator configuration are completed in the
browser guide at /setup.

-Cleanup stops this Compose project and removes its local images before build.
         PostgreSQL and Redis volumes are preserved.
-Build builds controller images locally instead of pulling them from GHCR.
-SourceBuild builds Docker images from Gitee/GitHub source repositories.
-AutoUpdate enables the controller's daily 04:00 automatic update.
-NoMirror skips mainland-China mirror registries and uses official GHCR.
-NoSourceFallback does not build from source when all image registries fail.
'@
    exit 0
}

$projectRoot = Split-Path -Parent $PSScriptRoot
if ($Build -and $SourceBuild) { throw '-Build 与 -SourceBuild 不能同时使用。' }
if (-not (Get-Command docker -ErrorAction SilentlyContinue)) { throw '需要安装 Docker Engine。' }
& docker compose version | Out-Null
if ($LASTEXITCODE -ne 0) { throw '需要 Docker Compose v2。' }

Push-Location $projectRoot
try {
    $envFile = Join-Path $projectRoot '.env'
    $utf8NoBom = New-Object System.Text.UTF8Encoding($false)
    $newPassword = {
        $bytes = New-Object byte[] 32
        $generator = [System.Security.Cryptography.RandomNumberGenerator]::Create()
        try { $generator.GetBytes($bytes) } finally { $generator.Dispose() }
        return -join ($bytes | ForEach-Object { $_.ToString('x2') })
    }
    $writeBootstrapEnv = {
        $password = & $newPassword
        $lines = @(
            '# Generated by the controller installer. Keep this file private.'
            'SPRING_PROFILES_ACTIVE=bootstrap'
            'POSTGRES_DB=guanlan_monitor'
            'POSTGRES_USER=guanlan'
            "POSTGRES_PASSWORD=$password"
            'CONTROLLER_AGENT_ENABLED=false'
        )
        [System.IO.File]::WriteAllLines($envFile, $lines, $utf8NoBom)
    }

    if (-not (Test-Path -LiteralPath $envFile)) {
        & $writeBootstrapEnv
    }
    elseif (-not (Select-String -LiteralPath $envFile -Pattern '^POSTGRES_PASSWORD=("[^"]+"|\S+)$' -Quiet)) {
        & $writeBootstrapEnv
    }
    & docker compose config --quiet
    if ($LASTEXITCODE -ne 0) { throw 'Compose 配置校验失败。' }

    if ($Cleanup) {
        Write-Host '清理 guanlan-monitor 旧容器和镜像（保留 PostgreSQL/Redis 卷）...'
        & docker compose down --remove-orphans --rmi local
        if ($LASTEXITCODE -ne 0) { throw '旧项目资源清理失败。' }
        $projectImageIds = @(& docker image ls --format '{{.Repository}} {{.ID}}' | ForEach-Object {
            $parts = $_ -split '\s+'
            if ($parts.Count -ge 2 -and $parts[0] -match '^guanlan-monitor(-|$)') { $parts[1] }
        } | Sort-Object -Unique)
        foreach ($imageId in $projectImageIds) {
            if ($imageId) { & docker image rm -f $imageId | Out-Null }
        }
    }

    $controllerServices = @('setup', 'server', 'web')
    if ($Build) {
        Write-Host '使用本地源码构建总控镜像...'
        & docker compose build --pull $controllerServices
    }
    else {
        Write-Host '正在拉取总控预构建镜像（优先使用国内镜像源）...'
        $updateScript = Join-Path $PSScriptRoot 'update-controller.ps1'
        $updateArgs = @('-Check')
        if ($SourceBuild) { $updateArgs += '-SourceBuild' }
        if ($NoMirror) { $updateArgs += '-NoMirror' }
        if ($NoSourceFallback) { $updateArgs += '-NoSourceFallback' }
        & $updateScript @updateArgs
    }
    if ($LASTEXITCODE -ne 0) { throw '总控镜像准备失败；如需本地构建请重试 -Build。' }
    & docker compose up -d --remove-orphans
    if ($LASTEXITCODE -ne 0) { throw '总终端服务器启动失败。' }

    $webPort = 18080
    if (Test-Path -LiteralPath $envFile) {
        $portLine = Select-String -LiteralPath $envFile -Pattern '^WEB_PORT=["'']?([0-9]+)["'']?$' | Select-Object -First 1
        if ($portLine -and $portLine.Matches[0].Groups[1].Value) {
            $webPort = [int]$portLine.Matches[0].Groups[1].Value
        }
    }
    $healthy = $false
    for ($attempt = 1; $attempt -le 40; $attempt++) {
        try {
            $health = Invoke-WebRequest -UseBasicParsing -Uri "http://127.0.0.1:$webPort/healthz" -TimeoutSec 3
            if ($health.StatusCode -eq 200) { $healthy = $true; break }
        }
        catch { }
        Start-Sleep -Seconds 3
    }
    if (-not $healthy) { throw 'Web 服务未在 120 秒内通过健康检查，请运行 docker compose ps 和 docker compose logs。' }
}
finally {
    Pop-Location
}

Write-Host "总终端服务器已启动。首次安装请打开 http://<服务器IP>:$webPort/setup。"
Write-Host "安装完成后，直接访问配置的域名根路径即可进入公开状态页，无需追加 /status。"
Write-Host 'PostgreSQL 已内置，数据库凭据由安装器自动生成，无需填写或执行数据库命令。'
Write-Host '向导只需设置站点入口、来源、时区和首个管理员。端口与绑定地址已在总终端启动前确定。'
Write-Host 'Windows 总终端默认不自动采集宿主机；请在设备管理中按普通 Windows Agent 流程接入。'
if ($AutoUpdate) {
    & (Join-Path $PSScriptRoot 'update-controller.ps1') -Auto
}
